name: Release

on:
  workflow_run:
    workflows: [Test Pull Request]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest

    outputs:
      nodeVersion: ${{ steps.bump_version.outputs.version }}
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    - name: yarn test
      run: |
        yarn
        yarn test
      env:
        CI: true
    - name: update cache
      run: |
        yarn build:cache
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff-index --quiet HEAD || git commit -m "updating cache"
        git push
    - name: bump version
      id: bump_version
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        echo "::set-output name=version::$(echo $(node -p "require('./package.json').version.trim()"))"
        yarn version --patch
        git push
  release:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    - name: draft release
      id: draft_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ needs.build.outputs.nodeVersion }}
        release_name: Release ${{ needs.build.outputs.nodeVersion }}
        body: |
          Releasing version ${{ needs.build.outputs.nodeVersion }} to NPM
        draft: true # Once tested this can be switched to false to immediately release to NPM
        prerelease: false
